"""Watchlist Tables

Revision ID: 3d33d437deb0
Revises: fe5cd922b3d5
Create Date: 2025-03-19 14:15:51.873404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d33d437deb0'
down_revision: Union[str, None] = 'fe5cd922b3d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_history', sa.Column('company_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_history', 'company_name')
    # ### end Alembic commands ###
