"""Create portfolio_snapshots table

Revision ID: 7157acbf5575
Revises: 3d33d437deb0
Create Date: 2025-03-21 19:54:52.773560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7157acbf5575'
down_revision: Union[str, None] = '3d33d437deb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_snapshots')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_investment', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('current_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_profit_loss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('overall_change_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='portfolio_snapshots_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='portfolio_snapshots_pkey')
    )
    # ### end Alembic commands ###
