"""Initial migration

Revision ID: 82bc2375d131
Revises: 
Create Date: 2025-03-04 14:18:41.914816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82bc2375d131'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('change', sa.Float(), nullable=False))
    op.add_column('user_stocks', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_stocks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_stocks', type_='foreignkey')
    op.drop_column('user_stocks', 'user_id')
    op.drop_column('stocks', 'change')
    # ### end Alembic commands ###
