"""Create watchlist and stockdata tables

Revision ID: fe5cd922b3d5
Revises: 1cefb49d3115
Create Date: 2025-03-17 02:34:15.952646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe5cd922b3d5'
down_revision: Union[str, None] = '1cefb49d3115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
